---
title: "exploratory_analysis"
author: "Samantha Kotkin, and Sophia Mu"
format: html
---

# Loading Libraries
```{r}
library(tidyverse)
library(ggplot2)
library(knitr)
```

# Data Loading

```{r}
Somerville_data <- read.csv("refined_somerville.csv")
View(Somerville_data)
```

# Tables

Correlations between Happiness and Life Satisfaction
```{r}
cor.test(Somerville_data$Somerville.Satisfaction.num, Somerville_data$Happiness.num, method = "pearson")
```

```{r}
# we also don't have some of these variables
Somerville_data |> 
  group_by(ID, Gender, Age, Race.Ethnicity) |>
  summarize(count = n()) |>
  kable()
```

## Sophia: 

### Exploratory data analyses
```{r}
#seeing total number of participants
Somerville_data |>
  summarize(count = n()) |>
  kable()
```

A lot of ppl preferred not to answer and very few Black and 2 or more races. -- idk if that is good or bad or if we can just note it in the limitations.  
```{r}
#just seeing number of people in each race because it will def affect analyses
Somerville_data |>
  group_by(Race.Ethnicity) |>
  summarize(raceCount = n()) |>
  kable()
```


```{r}
#function pt 2
findingMedian2 <- function(data){
 data |>
  group_by(Race.Ethnicity) |>
  summarize(across(c(Education.Quality.Satisfaction.num, Housing.Condition.Satisfaction.num, Feel.Part.Community.num, Somerville.Satisfaction.num, Happiness.num), median))
}
```

```{r}
findingMedian2(Somerville_data) |> kable()
```
## Histogram function
```{r}
s_data <- Somerville_data |>
  select(Education.Quality.Satisfaction.num, Housing.Condition.Satisfaction.num, Feel.Part.Community.num, Somerville.Satisfaction.num, Happiness.num)
```

```{r}
#idk if this is right
histogramFunction <- function(col, label, data){
  data |> 
  ggplot(aes(x = {{col}})) + 
  geom_histogram() +
  labs(x = label)
}
```

```{r}
map2(s_data, colnames(s_data), histogramFunction, Somerville_data)
```


