---
title: "overall_analysis"
author: "Amanda Stein"
format: html
---

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
Somerville_data <- read.csv("refined_somerville.csv")
```

Satisfaction with housing based on race, will fix labels if this is kept!
```{r}
ggplot(Somerville_data, aes(x = Housing.Condition.Satisfaction.num, y = Happiness.num)) +
  geom_point(position = position_jitter(width = 0.1, height = 0.1), alpha = 0.2 ) +
  theme_minimal()
```
```{r}
ggplot(Somerville_data, aes(x = Happiness.num, fill = Race.Ethnicity)) +
  geom_bar() +
  facet_wrap("Housing.Condition.Satisfaction.label") +
  theme_minimal()
```


```{r}
ggplot(Somerville_data, aes(x = Happiness.num, fill = Race.Ethnicity)) +
  geom_bar() +
  facet_wrap("Education.Quality.Satisfaction.label") +
  theme_minimal()
```

```{r}
barFunction <- function(var, label) {
  Somerville_data |>
    filter(var == {{var}}) |>
    ggplot(aes(x = Somerville.Satisfaction.num, fill = {{var}})) +
             geom_bar(position = "fill") + labs(title = "Satisfaction and Demographic Info", x = "Satisfaction Score", y = "Count", fill = label)
}

map2(Somerville_data, colnames(Somerville_data), barFunction)
```

```{r}
cor.test(Somerville_data$Somerville.Satisfaction.num, Somerville_data$Happiness.num, method = "pearson")
```
```{r}
library(reshape)
corData <- cor(Somerville_data [, c("Education.Quality.Satisfaction.num", "Housing.Condition.Satisfaction.num", "Feel.Part.Community.num", "Somerville.Satisfaction.num", "Happiness.num")])
corDataMelted <- melt(corData)

ggplot(corDataMelted, aes(x = X1, y = X2, fill = value)) +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1, 1), name = "Correlation") +
  geom_tile() + xlab("") + ylab("") +
  labs(title = ,
       fill = "Correlation") + theme_minimal()
```

