---
title: "data_tidying"
author: "Daniella Quihuis"
format: html
---

# Setting Up Environment
```{r}
library(tidyverse)
library(dplyr)

somerville_org <- read_csv("Data/Somerville_Happiness_Survey_Responses.csv") |> #loading csv
  filter(Year == 2025) |> #filtering to only responses from 2025
  select(ID, Year, Age, Gender, Race.Ethnicity, Household.Income, Education.Quality.Satisfaction.num, Education.Quality.Satisfaction.label, Housing.Condition.Satisfaction.num, Housing.Condition.Satisfaction.label, Feel.Part.Community.num, Feel.Part.Community.label, Somerville.Satisfaction.num, Somerville.Satisfaction.label, Happiness.num) #selecting desired variables
```

# Removing NAs
```{r}
somerville_na <- somerville_org |>
  drop_na() #removing NAs from dataframe
```

#Converting Characters to Factors
```{r}
somerville<- somerville_na |>
  mutate(across(where(is.character), as.factor)) #mutates across all variables where class is character and changes to factors
```


# Writing Refined Dataframe .csv file
```{r}
somerville  |>
    write.csv("refined_somerville.csv") #creates a new .csv file with refined data
```

